🚧 Update to SDK 26.1.100
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
👨🏿‍🦯🧑🏾‍⚖️👷🏼‍♂️👩🏻‍🎤

Full error log:
Error:  asset 2022-7-25--0-34-57--6c6151ce-480a-4e12-b75b-17a6c74a4191/main.min.js 108 KiB [emitted] (name: main) 1 related asset
runtime modules 727 bytes 4 modules
cacheable modules 101 KiB
javascript modules 101 KiB
./src/index.ts 3.12 KiB [built] [code generated] [7 errors]
./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 54.7 KiB [built] [code generated]
./node_modules/xyzt/dist/esm/xyzt.js 42.8 KiB [built] [code generated]
./assets/text-file-icon.svg 42 bytes [built] [code generated]
./package.json 638 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts
./src/index.ts 37:18-29
[tsl] ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts(37,19)
TS2345: Argument of type '{ priority: number; processFile({ file, boardPosition, willCommitArts, next }: { file: any; boardPosition: any; willCommitArts: any; next: any; }): Promise<any>; }' is not assignable to parameter of type 'IFileImportSupporter'.
Object literal may only specify known properties, and 'processFile' does not exist in type 'IFileImportSupporter'.

ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts
./src/index.ts 37:32-36
[tsl] ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts(37,33)
TS7031: Binding element 'file' implicitly has an 'any' type.

ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts
./src/index.ts 37:38-51
[tsl] ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts(37,39)
TS7031: Binding element 'boardPosition' implicitly has an 'any' type.

ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts
./src/index.ts 37:53-67
[tsl] ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts(37,54)
TS7031: Binding element 'willCommitArts' implicitly has an 'any' type.

ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts
./src/index.ts 37:69-73
[tsl] ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts(37,70)
TS7031: Binding element 'next' implicitly has an 'any' type.

ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts
./src/index.ts 50:44-49
[tsl] ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts(50,45)
TS2339: Property 'scale' does not exist on type 'BehaviorSubject<Transform>'.

ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts
./src/index.ts 55:20-33
[tsl] ERROR in C:\Users\me\work\collboard\sample-file-support\src\index.ts(55,21)
TS2554: Expected 7 arguments, but got 8.

webpack 5.35.1 compiled with 7 errors in 6544 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\sample-file-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\sample-file-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\sample-file-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\sample-file-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\sample-file-support\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\sample-file-support\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\sample-file-support\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\sample-file-support\node_modules\webpack\lib\Watching.js:201:28)